default-target = "wasm32-unknown-emscripten"

[target.emscripten]
# You can have a target-specific `prepend-js` key.
# prepend-js = "src/emscripten_runtime.js"
# This will enable Emscripten's SDL2 port. Consult Emscripten's documentation
# for more details.
link-args = ["-s", "USE_SDL=2"]